version: "3.5"

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: "America/New_York"
      WEBPASSWORD: "YOUR_SECRET_PIHOLE_PASSWORD" # CHANGE THIS TO A STRONG PASSWORD
      DNSMASQ_LISTENING: "all"
      PIHOLE_DNS_: "1.1.1.1;1.0.0.1" # Cloudflare DNS
    volumes:
      - "pihole_data:/etc/pihole"
      - "pihole_dnsmasq:/etc/dnsmasq.d"
    networks:
      - default
      - traefik_proxy # Assuming a Traefik network for reverse proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.your_domain.com`)" # Change to your desired domain
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls.certresolver=le"
      - "traefik.http.services.pihole.loadbalancer.server.port=80" # Pi-hole web interface listens on port 80 inside the container

networks:
  traefik_proxy:
    external: true
  default:
    driver: bridge

volumes:
  pihole_data:
  pihole_dnsmasq: