version: '3.8'
services:
  app:
    build:
      context: ../
      dockerfile: base.Dockerfile
    volumes:
      - ..:/workspaces:cached
    # Overrides default command so things don't shut down after the container starts.
    command: /bin/sh -c "while sleep 1000; do :; done"