apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/tailscale/tailscale"
    targetRevision: HEAD
    path: cmd/k8s-operator/deploy/chart
    helm:
      values: |
        replicaCount: 2
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
