apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: tailscale
  namespace: kube-system
spec:
  repo: https://pkgs.tailscale.com/helmcharts
  chart: tailscale-operator
  version: 1.82.5
  targetNamespace: tailscale
