apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.10.2
    chart: loki-stack
    helm:
      parameters:
        - name: grafana.enabled
          value: "true"
        - name: adminUser
          value: "admin"
        - name: adminPassword
          value: "password"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring