apiVersion: v1
kind: Service
metadata:
  name: grafana-loadbalancer
  namespace: monitoring
  labels:
    app: grafana-loki
spec:
  type: LoadBalancer
  loadBalancerClass: "tailscale"
  selector:
    app: grafana-loki
  ports:
    - name: https
      port: 443
      targetPort: 3000