apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 70.4.2
    helm:
      parameters:
        - name: prometheus.prometheusSpec.scrapeInterval
          value: 5s
    chart: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring


