# version: '3'
services:
  initContainer:
    image: busybox
    command: ['sh', '-c', 'chown -R 1000:1000 /home/node/.n8n']
    volumes:
      - n8n_data:/home/node/.n8n

  n8n:
    image: docker.n8n.io/n8nio/n8n:1.115.1
    platform: linux/aarch64
    restart: always
    container_name: n8n
    ports:
      - 5678:5678
    depends_on:
      - initContainer
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      # - N8N_PROTOCOL=https
      - N8N_HOST=n8n.dzo-byzantine.ts.net
      # - N8N_PORT=5678
      # - N8N_SECURE_COOKIE=false
    labels:
      - tsdproxy.enable=true
volumes:
  n8n_data:
    driver: local
  n8n-ts:
    driver: local

