version: '3'
services:
  n8n-ts:
    image: tailscale/tailscale:latest
    platform: linux/aarch64
    hostname: n8n
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/n8n.json
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
        - net_admin
        - sys_module
    volumes:
      - n8n-ts:/var/lib/tailscale
      - ./automation/config:/config

    restart: unless-stopped

  initContainer:
    image: busybox
    command: ['sh', '-c', 'chown -R 1000:1000 /home/node/.n8n']
    volumes:
      - n8n_data:/home/node/.n8n

  n8n:
    image: docker.n8n.io/n8nio/n8n:1.107.3
    platform: linux/aarch64
    restart: always
    container_name: n8n
    network_mode: service:n8n-ts
    depends_on:
      - n8n-ts
      - initContainer
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
    driver: local
  n8n-ts:
    driver: local
