# version: '3'
services:
  # n8n-ts:
  #   image: tailscale/tailscale:latest
  #   platform: linux/aarch64
  #   container_name: n8n-ts
  #   hostname: n8n
  #   environment:
  #     - TS_AUTHKEY=${TS_AUTHKEY}
  #     - TS_EXTRA_ARGS=--advertise-tags=tag:container
  #     - TS_STATE_DIR=/var/lib/tailscale
  #     - TS_SERVE_CONFIG=/config/n8n.json
  #   devices:
  #     - /dev/net/tun:/dev/net/tun
  #   cap_add:
  #       - net_admin
  #       - sys_module
  #   volumes:
  #     - n8n-ts:/var/lib/tailscale
  #     - ./config:/config
  #   restart: unless-stopped
  #
  initContainer:
    image: busybox
    command: ['sh', '-c', 'chown -R 1000:1000 /home/node/.n8n']
    volumes:
      - n8n_data:/home/node/.n8n

  n8n:
    image: docker.n8n.io/n8nio/n8n:1.112.3
    platform: linux/aarch64
    restart: always
    container_name: n8n
    ports:
      - 5678:5678
    depends_on:
      # - n8n-ts
      - initContainer
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_PROTOCOL=http
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=false

volumes:
  n8n_data:
    driver: local
  n8n-ts:
    driver: local

