version: '3'
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.106.3
    platform: linux/arm64
    restart: always
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - /opt/automation:/home/node/.n8n

