# version: '3.8'
services:
  n8n-ts:
    extends:
      file: ./automation/compose.yaml
      service: n8n-ts
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    privileged: true
    # network_mode: host
    ports:
      - 8123:8123
    volumes:
      - /opt/homeassistant/config:/config # TODO migrate from host storage to network volume 
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      TZ: America/Toronto

  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - /opt/paperless/redis:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.18.0
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - 8100:8000
    volumes:
      - /opt/paperless/data:/usr/src/paperless/data
      - /opt/paperless/media:/usr/src/paperless/media
      - /opt/paperless/consume:/usr/src/paperless/consume
      - /opt/paperless/export:/usr/src/paperless/export
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
