# version: '3.8'

include:
  - ./automation/compose.yaml
  - ./budget/compose.yaml
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - /etc/tsdproxy/config:/config
    restart: unless-stopped
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    privileged: true
    # network_mode: host
    ports:
      - 8123:8123
    volumes:
      - /opt/homeassistant/config:/config # TODO migrate from host storage to network volume
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      TZ: America/Toronto

  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - /opt/paperless/redis:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.18.4
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - 8100:8000
    volumes:
      - /opt/paperless/data:/usr/src/paperless/data
      - /opt/paperless/media:/usr/src/paperless/media
      - /opt/paperless/consume:/usr/src/paperless/consume
      - /opt/paperless/export:/usr/src/paperless/export
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "80:80/tcp" # Disabled since Traefik handles web access
    environment:
      TZ: 'America/Toronto'
      WEBPASSWORD: 'your_web_password' # Replace with your actual password
      PIHOLE_DNS_: '1.1.1.1;1.0.0.1' # Example upstream DNS servers
    volumes:
      - /opt/pihole/etc-pihole:/etc/pihole
      - /opt/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.yourdomain.com`)" # Replace with your domain
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls.certresolver=myresolver"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    networks:
      - default
      - proxy

volumes:
  datadir:
    external: true

networks:
  proxy:
    external: true
