version: '3.8'
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    privileged: true
    network_mode: host
    ports:
      - 8123:8123
    volumes:
      - /opt/homeassistant/config:/config # TODO migrate from host storage to network volume 
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: America/Toronto
