apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secrets-manager
spec:
  provider:
    gcpsm:
      projectID: gcloud-sandbox1
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-sa-secret
            key: secret-access-credentials