version: "3.8"

services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:1
    environment:
        TS_AUTHKEY: ${TS_AUTHKEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/tsdproxy_data:/data
      - ./config:/config
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
