version: "3.8"

x-common-config: &common-config
  restart: unless-stopped

services:
  tsdproxy:
    <<: *common-config
    image: almeidapaulopt/tsdproxy:2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tsdproxy_data:/data
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  tsdproxy_data: