version: "3.8"

services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:2
    # environment:
    #     TSDPROXY_AUTH: ${TSDPROXY_AUTH}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/tsdproxy_data:/data
      - ./config:/config
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    secrets:
      - tsdproxy_auth

secrets:
  tsdproxy_auth:
    environment: TSDPROXY_AUTH
