apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secrets-manager               # name of the SecretStore (or kind specified)
  target:
    name: operator-oauth  # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: tailscale-operator  # name of the GCPSM secret