apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
  - ../../../applications/app1/base

patchesStrategicMerge:
  - prometheus/patch.yaml
  - grafana/patch.yaml
  - alertmanager/patch.yaml
